name: app_environment
channels:
  - snowflake
dependencies:
  - pandas=2.3.1
  - python=3.9.*
  - snowflake=1.7.0
  - snowflake-connector-python=3.17.1
  - snowflake-ml-python=1.11.0
  - snowflake-snowpark-python=1.37.0
  - snowflake.core=1.7.0
  - streamlit=1.47.0
